name: Build e Deploy React

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.version.outputs.build_version }}
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Dependências
        run: npm install

      - name: Rodar Build
        run: npm run build

      - name: Gerar Versão
        id: version
        run: echo "::set-output name=build_version::$(date +'%Y%m%d%H%M%S')"

      - name: Copiar Build para Bucket Staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
          BUILD_VERSION: ${{ steps.version.outputs.build_version }}
        run: |
          aws s3 cp ./dist s3://itenorio.com-staging/$BUILD_VERSION --recursive
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Obter Versão do Build
        run: echo "Versão ${{ needs.build.outputs.build_version }}"
      - name: Copiar da Bucket de Staging para Bucket Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          BUILD_VERSION: ${{ needs.build.outputs.build_version }}
        run: |
          aws s3 sync s3://itenorio.com-staging/$BUILD_VERSION s3://itenorio.com --delete
